### ISSUE TITLE
Would I be able to post a modified version of your mission to steam?

### ISSUE THREAD

**Issue by Poopenshnapples** [RSpeekenbrink/ArmA-3-BECTI#14]
Hello, 
I made a version of your mission RHS-BECTI to have 3 teams
Guer(Resistance), West, East

I was hoping that I would be able to use your BECTI mod as the base for my mod, please!

Thank you for your awesome work.. I know how much time goes into these things!

**Comment by RSpeekenbrink** [comment]
Hey Poopenshnapples, 

If you link to this version &[ the original version by Benny](http://www.armaholic.com/page.php?id=22985) go for it :)

**Comment by Poopenshnapples** [comment]
Thank you so much Remco! :D


________________________________
