### ISSUE TITLE
Sandbag bunkers block the road, tougher for ai to drive?

### ISSUE THREAD

**Issue by Emton** [RSpeekenbrink/ArmA-3-BECTI#15]
It seems like the big square sandbag bunker that spawns in towns are usually blocking a good portion of the road and make an obstacle for ai driving, really it would be better no bunker in the road (maybe somewhere else, open and flat terrain) Better if the already bad arma driving ai doesn't have an even tougher time.

**Comment by RSpeekenbrink** [comment]
I agree, when we pick up the development again this will be improved

**Comment by RSpeekenbrink** [comment]
Will be fixed in rewrite
