### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Stijnn** [RSpeekenbrink/ArmA-3-BECTI#2]
**Arma 3 Version:** `x.xx` (stable / rc / dev)

**Mods:**
- `@RHSUSAF`
- `@RHSAFRF`

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue.

**Steps to reproduce:**
- Add the steps needed to reproduce the issue.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Comment by RSpeekenbrink** [comment]
Invalid Issue Stijnn, you should know that ;)
