### ISSUE TITLE
Building assets have different functionality from player to player

### ISSUE THREAD

**Issue by 2joocy** [RSpeekenbrink/ArmA-3-BECTI#4]
**Arma 3 Version:** `x.xx` (stable / rc / dev)

**Mods:**
- `@RHSUSAF`
- `@RHSAFRF`

**Description:**
When adding different factories to your base, a common issue would occour, where each building might have different uses for each player. A example of this would be that my squad leader added a light vehicle factory, where I was shown a heavy vehicle factory which was not unlocked yet (However it showed on my client, and was functional). 

**Steps to reproduce:**
- Create a factory (Light Vehicle).
- Have different players at the base
- Join a ongoing game
- Inspect the building created (Should say Light Vehicle, but does say Heavy Vehicle).

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

PS: Please add ACE support!

**Comment by RSpeekenbrink** [comment]
> PS: Please add ACE support!

ACE Support is available in the main branch now, will be included in next release

Thanks for reporting, we will look into it ASAP

**Comment by RSpeekenbrink** [comment]
So far I havent been able to reproduce, How exactly did you get this problem?

**Comment by RSpeekenbrink** [comment]
Reproduced, will fix it asap
