### ISSUE TITLE
Equipment menu doesnt show

### ISSUE THREAD

**Issue by 2joocy** [RSpeekenbrink/ArmA-3-BECTI#5]
**Arma 3 Version:** `x.xx` (stable / rc / dev)

**Mods:**
- `@RHSUSAF`
- `@RHSAFRF`

**Description:**
Upon joining a already ongoing mission, the equipment menu often dont show up for players

**Steps to reproduce:**
Seems to be happening periodically, when you join a ongoing game

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Comment by RSpeekenbrink** [comment]
Reproduced, will fix asap

**Comment by RSpeekenbrink** [comment]
Seems like it has to do with the buildings glitch. When the JIP Player joins and their barrack switched to NAVAL they wont have a barrack and thereby not able to get in the equipment menu. So will fix in #4
