### ISSUE TITLE
Changing the number of towns won't do anything

### ISSUE THREAD

**Issue by RSpeekenbrink** [RSpeekenbrink/ArmA-3-BECTI#7]
**Arma 3 Version:** 1.70 stable

**Mods:**
- `@RHSUSAF`
- `@RHSAFRF`
- `@RHSGREF`

**Description:**
Changing the town amount in the mission parameters won't do anything

**Steps to reproduce:**
- start a session
- change town amount parameter

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Comment by RSpeekenbrink** [comment]
Has to do with the game logic on the template, its not configured correctly, will fix it when I can.

**Comment by johnsmm** [comment]
Hi Speeken, can you add me to steam admin@ofps.net or discord Omon XR
